### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by dariopetraroia** [CodyHouse/cd-responsive-sidebar-changelog#6]
Hy,

I noticed a performance issue on mobile with transitions in some components for example in the side panel.

Please check the screen recording I made:

https://filebin.net/qfhgacaj7m5zd315/IMG_0475.MP4

I am using chrome on IPhone 12 pro

Thanks

**Comment by claudia-romano** [comment]
Hi Dario,
it does not look like a performance issue but more like the translate is not working properly (if you test those components, the panel should slide in rather than fade).

I have tested it on a iPhone 12 Chrome and I was not able to reproduce the issue. I suppose you are using a virtual machine. Do you have a real device you can use to test it? Or could you try to test the component outside the iframe? For example, using this link:
https://codyhouse.co/app/components/demo/demo-advanced-filter

Thanks

**Comment by dariopetraroia** [comment]
Hy Claudia, i tested this on my real device and the issue persist also with the link outside the iframe...

https://user-images.githubusercontent.com/5861215/145596060-516a9eca-cf01-49d0-a43d-fca412828605.mp4

Can you try to open the link twice:
https://codyhouse.co/app/components/demo/demo-advanced-filter 
in 2 tabs and click first one "Show filter" button and then the other?

thanks

**Comment by dariopetraroia** [comment]
Hello Claudia, I was able to fix this with a workaround by removing the css transition property using a notransition class…

.no-transition {
  -webkit-transition: none !important;
  -moz-transition: none !important;
  -o-transition: none !important;
  transition: none !important;
}

**Comment by claudia-romano** [comment]
Hi Dario, we are still looking into this (we are not able to recreate the issue on our side). What OS are you using? Thanks.

**Comment by dariopetraroia** [comment]
Hy Claudia, sorry for the late reply... I am using ios 15.2 but when i disabel transition i do not have this slow slide effect. Don't worry about it i will have transition disabled for my app. Thank you
