### ISSUE TITLE
Issue re-reinitialize component

### ISSUE THREAD

**Issue by dariopetraroia** [CodyHouse/cd-responsive-sidebar-changelog#7]
Hy, i have a little problem whe I try to re-intialize a component. 
For example when I reload a partial with the open sidebar button; This button will not work untill i reinitialize the component.
But following the codyframe documentation (https://codyhouse.co/ds/docs/components#reinit-components) when I write:

new Sidebar()

Uncaught ReferenceError: Sidebar is not defined
at <anonymous>:1:1

this because Sidebar is inside a (function() {}());

can you please have a look on this?

Ciao ;)

Dario

**Comment by claudia-romano** [comment]
Hi Dario, we have updated the responsive sidebar component to make the `Sidebar` object public. More info here:
https://codyhouse.co/ds/components/info/responsive-sidebar#dynamic-content

Note that if your sidebar is not dynamically loaded but only your trigger is, then you should use the `openSidebar` event (dispatch it when clicking on your new trigger) rather than re-init the sidebar. More info here:
https://codyhouse.co/ds/components/info/responsive-sidebar#custom-events
